# .github/workflows/build.yml
name: Build Electron

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Electron
        run: npm run build:electron

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bereal-toolkit-${{ matrix.os }}
          path: dist/
